// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhjxgbonoiajzljvnyjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oanhnYm9ub2lhanpsanZueWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NDM4ODcsImV4cCI6MjA1MDAxOTg4N30.RspqdGBgpXxXzjVYZHA58_w8QdMg_Q8xqEM1ZQtvjxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);